### PR TITLE
Update deltapatcher.po

### PR DESCRIPTION
**Pull request by Felipefpl**
Hi, i updated the translation to pt-br, please check if all places in the GUI upscale because translated words are bigger than in english language.

### CODE REVIEW

**Comment by marco-calautti** [comment]
You can test it yourself. Just convert the po file to mo using this online service: https://po2mo.net/

The just create the folder resources/pt_BR and put deltapatcher.mo in it. Run deltapatcher and you should see the transaltion applied, if your system is set to pt_BR.

**Comment by marco-calautti** [comment]
Could you point me to these sentences?

**Comment by Felipefpl** [comment]
Just check the expressions not covered by the translation, there are a few of them, i cant show each one of them or i'll have to take a lot of pics for them.

**Comment by Felipefpl** [comment]
Is there any reason why this wasnt submitted yet?

**Comment by marco-calautti** [comment]
Because I am phasing out translations. The tool is so simple that having translations is not that relevant, and would only force to package Delta Patcher with additional external files. I would like that Delta Patcher is just a single executable, and nothing more.

**Comment by Felipefpl** [comment]
Ok then.

**Pull request closed without merging**
